### ISSUE TITLE
Sklearn.externals

### ISSUE THREAD

**Issue by StevenWilliams** [albahnsen/pyea#1]
It seems like you're library being used by costcla is depending on an outdated sklearn module.
It seems to have been fixed for costcla, in https://github.com/albahnsen/CostSensitiveClassification/commit/92e40edb32c44fbcadcbe7839ee83dcb5e7e131e, which is the version I've been using of costcla (the version in the pip repo is outdated so it needs to be updated).

ModuleNotFoundError: No module named 'sklearn.externals.joblib'

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-3c04ac789098> in <module>
----> 1 from costcla.metrics import cost_loss, savings_score
      2 from costcla.models import CostSensitiveLogisticRegression, CostSensitiveDecisionTreeClassifier
      3 cost_mat_train = np.zeros((len(y_train),4))
      4 #false positives cost 5
      5 cost_mat_train[:,0]=1

~/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/costcla/__init__.py in <module>
     29 from .metrics import *
     30 from .datasets import *
---> 31 from .models import *
     32 

~/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/costcla/models/__init__.py in <module>
      4 
      5 from .directcost import BayesMinimumRiskClassifier, ThresholdingOptimization
----> 6 from .regression import CostSensitiveLogisticRegression
      7 from .cost_tree import CostSensitiveDecisionTreeClassifier
      8 

~/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/costcla/models/regression.py in <module>
     11 from sklearn.base import BaseEstimator
     12 # from sklearn.linear_model.logistic import _intercept_dot
---> 13 from pyea import GeneticAlgorithmOptimizer
     14 from ..metrics import cost_loss
     15 

~/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/pyea/__init__.py in <module>
     11 
     12 
---> 13 from .models import *

~/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/pyea/models/__init__.py in <module>
----> 1 from .ga import GeneticAlgorithmOptimizer

~/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/pyea/models/ga.py in <module>
     10 import pandas as pd
     11 from scipy.stats import norm
---> 12 from sklearn.externals.joblib import Parallel, delayed, cpu_count
     13 import itertools
     14 

ModuleNotFoundError: No module named 'sklearn.externals.joblib'

```

**Comment by jairojuunior** [comment]
@StevenWilliams  I've got the same problem here. Just fixed it. 
@albahnsen I'll push a fix to this bug. It's similar to https://github.com/albahnsen/CostSensitiveClassification/issues/22

**Comment by vishnup85** [comment]
I am facing the same issue. Was this issue fixed. 
I am using python3.9 with sklearn version '1.0.2'

**Comment by jairojuunior** [comment]
> I am facing the same issue. Was this issue fixed. I am using python3.9 with sklearn version '1.0.2'

@vishnup85 , I submitted a commit fixing this issue, but it wasn't neither merged nor reviewed.  I'd recommend you cloning from my commited version (https://github.com/jairojuunior/pyea) and installing it (just run python start.py install).

**Comment by albahnsen** [comment]
Hi guys sorry my late response. Can I add you as a admin to this project?

**Comment by jairojuunior** [comment]
> Hi guys sorry my late response. Can I add you as a admin to this project?

Hi @albahnsen  nice to meet you. Please, add me as admin if you can. I would also appreciate to contribute to costcla, if possible.

**Comment by vishnup85** [comment]
@albahnsen Good to e-meet you. Please, add me as well if you can.

**Comment by vishnup85** [comment]
@jairojuunior I followed the steps you mention but I still face the issue when importing below libraries: 
```
from costcla.metrics import cost_loss, savings_score
from costcla.models import CostSensitiveLogisticRegression, CostSensitiveDecisionTreeClassifier
```

**Comment by jairojuunior** [comment]
@vishnup85  could you provide the full error, please?

**Comment by vishnup85** [comment]
@jairojuunior Please find below:

```
ModuleNotFoundError                       Traceback (most recent call last)
C:\Users\VISHNU~1.PRA\AppData\Local\Temp/ipykernel_26352/3394926948.py in <module>
      1 from costcla.metrics import cost_loss, savings_score
----> 2 from costcla.models import CostSensitiveLogisticRegression, CostSensitiveDecisionTreeClassifier

~\Anaconda3\envs\detention_model2\lib\site-packages\costcla\__init__.py in <module>
     29 from .metrics import *
     30 from .datasets import *
---> 31 from .models import *
     32 

~\Anaconda3\envs\detention_model2\lib\site-packages\costcla\models\__init__.py in <module>
      4 
      5 from .directcost import BayesMinimumRiskClassifier, ThresholdingOptimization
----> 6 from .regression import CostSensitiveLogisticRegression
      7 from .cost_tree import CostSensitiveDecisionTreeClassifier
      8 

~\Anaconda3\envs\detention_model2\lib\site-packages\costcla\models\regression.py in <module>
     11 from sklearn.base import BaseEstimator
     12 # from sklearn.linear_model.logistic import _intercept_dot
---> 13 from pyea import GeneticAlgorithmOptimizer
     14 from ..metrics import cost_loss
     15 

~\Anaconda3\envs\detention_model2\lib\site-packages\pyea\__init__.py in <module>
     11 
     12 
---> 13 from .models import *

~\Anaconda3\envs\detention_model2\lib\site-packages\pyea\models\__init__.py in <module>
----> 1 from .ga import GeneticAlgorithmOptimizer

~\Anaconda3\envs\detention_model2\lib\site-packages\pyea\models\ga.py in <module>
     10 import pandas as pd
     11 from scipy.stats import norm
---> 12 from sklearn.externals.joblib import Parallel, delayed, cpu_count
     13 import itertools
     14 

ModuleNotFoundError: No module named 'sklearn.externals.joblib'
```

**Comment by jairojuunior** [comment]
@vishnup85 I think you weren't able to successfully install the version from my repo (you can see that the line 12 on this file (https://github.com/jairojuunior/pyea/blob/master/pyea/models/ga.py) was altered from what's in your log).
Please do as follows:
pip uninstall costcla # if you have costcla installed
pip uninstall pyea
git clone https://github.com/jairojuunior/pyea
cd pyea
python setup.py install

Also, I've recently found that the costcla version in PyPi has a deprecated dependency, so I'd suggest cloning the official github repository and installing it from there, since this problem seems to be fixed by a push recently. 
PS: I'll merge my fix to this problem in the next few days here, so please tell me if you were able to fix your problem using my solution.

**Comment by vishnup85** [comment]
@jairojuunior Thanks a lot for your detailed instruction. It works now and the error is gone once I install costcla from source instead of PyPi. :)
